# Generated by Django 2.2 on 2022-08-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(default='new', max_length=15, verbose_name='Модерация'),
        ),
    ]
